ROWS = 18
COLS = 32
TILE_SIZE = 40
SIDE_PANEL = 300
SCREEN_HEIGHT = TILE_SIZE * ROWS
SCREEN_WIDTH = TILE_SIZE * COLS
FPS = 60

#trooper constants
TROOPER_LEVELS = 4
ANIMATION_FRAMES = 8
ANIMATION_DELAY = 15

#enemy constants
ENEMY_LEVELS = 4