ROWS = 18
COLS = 32
TILE_SIZE = 40
SIDE_PANEL = 300
SCREEN_HEIGHT = TILE_SIZE * ROWS
SCREEN_WIDTH = TILE_SIZE * COLS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 4

#trooper constants
TROOPER_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 1
LEVEL_COMPLETE_REWARD = 100
ANIMATION_FRAMES = 8
ANIMATION_DELAY = 15
DAMAGE = 5

#enemy constants
ENEMY_LEVELS = 4
SPAWN_COOLDOWN = 500

